"""Render a final SUMMARY.md from all the per-cell artifacts on disk.

The auto-generated SUMMARY.md from run_metrics.py only reflects the
last invocation (which was --skip-validity --skip-coverage
--skip-bug-bench), so validity/coverage/bug-bench rows are missing.
This script walks the artifact tree directly and produces a complete
report.
"""

from __future__ import annotations

import json
from pathlib import Path

E1_ROOT = Path(__file__).resolve().parent
RESULTS_ROOT = E1_ROOT / "results"
METRICS_ROOT = RESULTS_ROOT / "metrics"


def _load_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def _validity_row(sut: str, fmt: str) -> str:
    p = METRICS_ROOT / "validity" / f"{sut}_{fmt.lower()}.json"
    d = _load_json(p)
    if d is None:
        return f"- **{sut}**: ⚠ probe failed (runner unavailable / unsupported)"
    r = d.get("validity_ratio")
    ps = d.get("parse_success", "?")
    tot = d.get("generated_total", "?")
    if r is None:
        return f"- **{sut}**: ❌ no ratio"
    return f"- **{sut}**: **{r*100:.1f}%** ({ps}/{tot})"


def _mutation_row(sut: str, fmt: str) -> str:
    p = METRICS_ROOT / "mutation" / f"{sut}_{fmt.lower()}" / "summary.json"
    d = _load_json(p)
    if d is None:
        return (
            f"- **{sut}_{fmt.lower()}**: ⚠ no summary "
            f"(see `mutation/{sut}_{fmt.lower()}/stderr.txt`)"
        )
    # Atheris driver writes nested mutation_score; mutation_driver writes
    # flat. Handle both.
    if "mutation_score" in d:
        ms = d["mutation_score"]
        score = ms.get("score")
        killed = ms.get("killed", "?")
        reachable = ms.get("reachable", "?")
    else:
        score = d.get("score")
        killed = d.get("killed", "?")
        reachable = d.get("reachable", "?")
    if score is None:
        return f"- **{sut}_{fmt.lower()}**: ❌ no score in summary"
    return f"- **{sut}_{fmt.lower()}**: **{score*100:.2f}%** ({killed}/{reachable})"


def _coverage_row(fmt: str) -> str:
    cov_dir = RESULTS_ROOT / fmt.lower() / "coverage"
    if not cov_dir.exists():
        return "- (no coverage dir)"
    artifacts = list(cov_dir.rglob("*"))
    n_files = sum(1 for a in artifacts if a.is_file())
    total = sum(a.stat().st_size for a in artifacts if a.is_file())
    return f"- **{fmt}**: {n_files} artifacts, {total/1024:.1f} KB total under `{cov_dir.name}/`"


def _bug_bench_section() -> list[str]:
    agg = METRICS_ROOT / "bug_bench" / "aggregate.json"
    d = _load_json(agg)
    lines = ["## Bug Bench (real-bug detection)", ""]
    if d is None:
        # no aggregate — show file count
        per_bug = list((METRICS_ROOT / "bug_bench" / "biotest").rglob("result.json")) \
            if (METRICS_ROOT / "bug_bench" / "biotest").exists() else []
        lines.append(f"- aggregate.json missing; found {len(per_bug)} per-bug results under `bug_bench/biotest/`")
        return lines
    # try common shapes
    if isinstance(d, dict):
        for k, v in d.items():
            lines.append(f"- **{k}**: {v}")
    elif isinstance(d, list):
        lines.append(f"- {len(d)} entries; first: {d[0] if d else 'empty'}")
    else:
        lines.append(f"- {d}")
    return lines


def _e1_run_summary() -> list[str]:
    lines = ["## E1 Pipeline Summary", ""]
    for fmt in ("vcf", "sam"):
        log = RESULTS_ROOT / fmt / "run.log"
        if not log.exists():
            continue
        text = log.read_text(encoding="utf-8", errors="replace")
        # Find Phase milestones
        lines.append(f"### {fmt.upper()} run")
        for marker in ("Phase B:", "Phase C:", "Phase D:", "Phase E:",
                       "DET Rate", "Bugs / DETs", "Total Pipeline",
                       "Final SCC", "Termination"):
            for line in text.splitlines():
                if marker in line:
                    lines.append(f"- {line.strip()}")
                    break
        lines.append("")
    return lines


def main():
    lines = [
        "# E1 (Phase A ablation) — Final Metrics Summary",
        "",
        "Generated by `render_final_summary.py` from per-cell artifacts under `results/metrics/`.",
        "",
        "**Configuration**: BioTest with naive prompt-stuffing replacing RAG retrieval. "
        "Phase D feedback loop fully enabled. Zero source code modification "
        "(four runtime monkey-patches only).",
        "",
    ]

    # --- E1 pipeline summary ---
    lines += _e1_run_summary()

    # --- Validity ---
    lines += ["## Validity Ratio (per SUT × format)", ""]
    for fmt in ("VCF", "SAM"):
        lines += [f"### {fmt}", ""]
        eligible = {
            "VCF": ["htsjdk", "vcfpy", "noodles", "pysam", "htslib", "reference"],
            "SAM": ["htsjdk", "biopython", "seqan3", "pysam", "htslib", "reference"],
        }[fmt]
        for sut in eligible:
            lines.append(_validity_row(sut, fmt))
        lines.append("")

    # --- Coverage ---
    lines += ["## Coverage Artifacts", ""]
    for fmt in ("VCF", "SAM"):
        lines.append(_coverage_row(fmt))
    lines.append("")
    lines.append("Coverage was captured live during Phase D by JaCoCo (htsjdk), "
                 "coverage.py (vcfpy/biopython/pysam), gcovr (seqan3), and "
                 "cargo-llvm-cov (noodles). Artifacts are under `results/{vcf,sam}/coverage/`. "
                 "Full per-line growth aggregation requires a separate "
                 "`compares/scripts/coverage_rollup.py` invocation against "
                 "`growth_<idx>.json` files (not produced in this single-rep E1 run).")
    lines.append("")

    # --- Mutation ---
    lines += ["## Mutation Score", ""]
    cells = [
        ("htsjdk", "VCF"), ("vcfpy", "VCF"), ("noodles", "VCF"),
        ("htsjdk", "SAM"), ("biopython", "SAM"), ("seqan3", "SAM"),
    ]
    for sut, fmt in cells:
        lines.append(_mutation_row(sut, fmt))
    lines.append("")

    # --- Bug bench ---
    lines += _bug_bench_section()
    lines.append("")

    # --- Limitations ---
    lines += [
        "## Known Limitations",
        "",
        "* **htsjdk_{vcf,sam} mutation (PIT)**: `phase3_jazzer_pit.sh` expects "
        "  PIT JARs at host `/opt/pit/` (baked into `biotest-bench:latest` Docker image). "
        "  Extracting them to host requires explicit user authorization that wasn't "
        "  granted in this run. Workaround: run the script inside the container, "
        "  or `docker cp biotest-bench:latest:/opt/pit ...` to host then set `PIT_DIR`.",
        "* **vcfpy_vcf mutation**: returned 0/0 (no reachable mutants). Likely vcfpy's "
        "  permissive parser treats most E1-generated transformed files as parseable "
        "  but doesn't exercise the mutated lines. Worth investigating.",
        "* **Validity probe missing 4 cells**: noodles binary unavailable on this host, "
        "  htslib runner has a class-name mismatch in `validity_probe.py`, reference "
        "  is not in the probe's `--sut` choice list.",
        "",
    ]

    out = METRICS_ROOT / "FINAL_SUMMARY.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"FINAL_SUMMARY -> {out}")


if __name__ == "__main__":
    main()
