#!/usr/bin/env python3
"""Aggregate 4-rep BioTest coverage into a per-SUT mean/std table."""
from __future__ import annotations

import argparse
import json
import math
import statistics
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-root", type=Path,
                    default=Path(__file__).resolve().parents[2]
                    / "compares" / "results" / "coverage" / "biotest_4rep_20260423")
    args = ap.parse_args()

    # Collect every per-rep measurement.json under the out root. This is
    # robust across partial reruns (the orchestrator overwrites
    # results.json each sweep, but per-rep dirs accumulate across sweeps).
    measurements = sorted(args.out_root.rglob("measurement.json"))
    if not measurements:
        print(f"no measurement.json files under {args.out_root}")
        return 1
    records: list[dict] = []
    for p in measurements:
        try:
            records.append(json.loads(p.read_text(encoding="utf-8")))
        except Exception as e:
            print(f"skip {p}: {e}")

    # Group by (sut, format) cell.
    buckets: dict[tuple[str, str], list[dict]] = {}
    for r in records:
        key = (r["sut"], r["format"])
        buckets.setdefault(key, []).append(r)

    lines: list[str] = []
    lines.append("# BioTest — 4-rep full-pipeline coverage summary (mean ± std)")
    lines.append("")
    lines.append(
        "Generated by `compares/scripts/biotest_4rep_aggregate.py`. Each "
        "row reports the **end-of-Phase-D** line coverage over 4 "
        "independent reps of `biotest.py --phase A,D` (Phase A spec ingest, "
        "then Phase D's iterative B + C feedback loop), measured through "
        "the per-SUT filter in `biotest_config.yaml: coverage.target_filters`."
    )
    lines.append("")
    lines.append("## Setup")
    lines.append("")
    lines.append("- **Phases run per rep**: A, D (Phase D internally drives Phase B mining + Phase C cross-execution per iteration).")
    lines.append("- **Reps per cell**: 4 (rep 0..3) — each rep starts from empty mr_registry, feedback_state, rule_attempts (independent reps).")
    lines.append("- **Per-rep seed RNG**: 42 + rep index.")
    lines.append("- **Phase D max_iterations**: 4 for `htsjdk/VCF` (initial run; canonical Run 6 baseline), 2 for SAM cells (per `biotest.py` SAM auto-default), 1 for `vcfpy/VCF` re-sweep (after timeout-kill data loss on max_iter=4 — see notes).")
    lines.append("- **Seeds per rep**: 10 per format (Tier-1 curated; vcfpy/VCF re-sweep used 5 to fit the 90-min wall cap).")
    lines.append("- **Wall-clock cap**: 90 min/VCF, 60 min/SAM. biotest's own `feedback_control.timeout_minutes=80` was active for vcfpy/SAM cells (after the host sweep set it) so biotest could self-terminate cleanly between iterations and let coverage.py flush before the wall cap fired.")
    lines.append("- **Coverage artefacts reset between reps**: `jacoco.exec/.xml`, `.coverage`, etc. So each rep's reading reflects only that rep's work.")
    lines.append("- **LLM**: DeepSeek V3 (`deepseek-chat`) drove Phase B mining and Phase D blindspot tickets each iteration.")
    lines.append(f"- **Output dir**: `{args.out_root.relative_to(Path(__file__).resolve().parents[2]) if str(args.out_root).startswith(str(Path(__file__).resolve().parents[2])) else args.out_root}`.")
    lines.append("")
    lines.append("## Per-SUT coverage")
    lines.append("")
    lines.append(
        "| SUT | Format | Reps | Mean line % | Std (pp) | Min | Max | "
        "Mean covered/total | Avg wall (s) | Notes |"
    )
    lines.append(
        "|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---|"
    )

    rows_for_sort = []
    for (sut, fmt), reps in sorted(buckets.items()):
        pcts = [float(r.get("line_pct", 0.0)) for r in reps]
        covered = [int(r.get("covered", 0)) for r in reps]
        totals = [int(r.get("total", 0)) for r in reps]
        wall = [float(r.get("elapsed_s", 0.0)) for r in reps]
        mean_p = statistics.fmean(pcts) if pcts else 0.0
        std_p = (statistics.stdev(pcts)
                 if len(pcts) >= 2 else 0.0)
        min_p = min(pcts) if pcts else 0.0
        max_p = max(pcts) if pcts else 0.0
        mean_cov = round(statistics.fmean(covered)) if covered else 0
        mean_tot = round(statistics.fmean(totals)) if totals else 0
        mean_wall = round(statistics.fmean(wall)) if wall else 0
        notes: list[str] = []
        statuses = {r.get("status", "?") for r in reps}
        if statuses - {"ok"}:
            notes.append(f"status={','.join(sorted(statuses))}")
        nonzero_exits = [r for r in reps if r.get("exit_code", 0) != 0]
        if nonzero_exits:
            notes.append(f"{len(nonzero_exits)} non-zero exits")
        rows_for_sort.append((sut, fmt, len(reps), mean_p, std_p, min_p,
                              max_p, mean_cov, mean_tot, mean_wall,
                              "; ".join(notes) or "—"))

    # Sort rows: VCF first, then SAM; alphabetical SUT.
    rows_for_sort.sort(key=lambda r: (r[1], r[0]))
    for row in rows_for_sort:
        sut, fmt, n, mean_p, std_p, min_p, max_p, cov, tot, wall, note = row
        lines.append(
            f"| {sut} | {fmt} | {n} | {mean_p:.2f}% | ±{std_p:.2f} | "
            f"{min_p:.2f}% | {max_p:.2f}% | {cov}/{tot} | {wall} | {note} |"
        )

    lines.append("")
    lines.append("")
    lines.append("## Caveats on the cells in the table")
    lines.append("")
    lines.append("- **pysam (VCF & SAM) not listed**: pysam's parser logic is Cython-compiled `libcbcf.pyx` / `libcsam*.pyx` → native `.so`; `coverage.py` cannot trace it. Per README §SUT Matrix, pysam is a **voter only**, not a coverage primary, so it's omitted from this 4-rep table.")
    lines.append("- **vcfpy/VCF used `max_iterations=1` and 5 seeds** — Phase D's max_iter=4 + 10 seeds caused 3 of 4 reps to overshoot the 90-min wall cap on a Phase-C iteration that hadn't yet flushed coverage.py's SQLite. Single iteration with 5 seeds finishes cleanly in ~50 min and gave 4/4 valid reps. Coverage value (74.10–74.70%) sits comfortably above the canonical Run 1 (`coverage_notes/vcfpy/vcf/biotest.md`) baseline of 73.4%.")
    lines.append("- **htsjdk/VCF used `max_iterations=4` and 10 seeds** (canonical Run 6 settings); JaCoCo's exec file is appended during execution so a wall-cap kill still preserved data — all 4 reps valid. Mean 47.32% sits above the Run 6 baseline of 46.9%.")
    lines.append("- **htsjdk/SAM and biopython/SAM** used `max_iterations=2` (per `biotest.py` SAM auto-default after Run 11). All 4 reps valid in each cell.")
    lines.append("- **noodles/VCF ran inside `biotest-bench:latest` Docker container** (host has no `cargo` / `rustc`). Initial container attempts failed because `cargo llvm-cov 0.8.5`'s `report --json` subcommand only enumerates workspace packages — the external `noodles-vcf` crate's instrumentation never surfaced. Workaround: bypass `cargo llvm-cov report` and drive the rust-bundled `llvm-profdata merge` + `llvm-cov export` directly against the binary built with `RUSTFLAGS=-C instrument-coverage cargo build --release`. With this, the report enumerates 168 noodles-vcf files (matching Apr 21 archived runs at noodles-vcf 0.57.0). Used `max_iterations=2` per rep × 4 reps × 5 seeds × ~20 min = ~80 min total. Cargo.toml was bumped from `noodles-vcf = \"0.23\"` (broken — APIs in `src/main.rs` reference `vcf::variant::io::Write` etc. from 0.30+) to `\"0.57\"` (matches archived runs); `vcfpy/VCF` and `htsjdk/VCF` cells in the host sweep ran with `noodles` as a voter at the standard release binary (no host coverage instrumentation needed for voter-only role).")
    lines.append("- **seqan3/SAM also ran inside `biotest-bench:latest`** because the host MinGW harness doesn't link seqan3. `harnesses/cpp/biotest_harness.cpp` was patched to add an opt-in seqan3 pre-pass via `#ifdef USE_SEQAN3` — when the harness is rebuilt with `clang++-18 -std=c++23 -DUSE_SEQAN3 -DSEQAN3_DISABLE_COMPILER_CHECK -fprofile-arcs -ftest-coverage -isystem /opt/seqan3/include`, it now runs `seqan3::sam_file_input` over the input file BEFORE the existing text parser (canonical-JSON output is byte-identical between USE_SEQAN3 and plain builds, so oracle behaviour is unchanged). Coverage is collected by gcovr 8.6 against the `seqan3/io/sam_file`, `format_sam`, `cigar` filter — same scope `aflpp × seqan3` (79 %), `pure_random × seqan3` (78 %), and `libfuzzer × seqan3` use in `compares/results/coverage/ALL_SUT_COVERAGE.md`. Used `max_iterations=2` per rep × 4 reps × 5 seeds × ~20 min = ~78 min total. The 9-of-586 SAM seeds that segfault under seqan3 (concept-instantiation aborts on certain header configurations) are caught by the `try/catch` wrapper around the seqan3 call; the text parser still runs and produces canonical JSON.")
    lines.append("- **Std is small** because each rep's Phase B re-mines a similar MR set against the same small seed corpus and Phase C is largely deterministic given identical seeds + voter registry. The variance source is Hypothesis's strategy RNG when MR-driven generators fire on a particular seed; with a small corpus those firings overlap heavily across reps. Larger corpora and Phase D's synthesized seeds (off in this sweep — `seed_synthesis: false`) would widen the band materially.")
    lines.append("")
    lines.append("## Per-rep detail")
    lines.append("")
    lines.append(
        "| SUT | Format | Rep | Exit | Line % | Covered/Total | Wall (s) | Status |"
    )
    lines.append(
        "|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---|"
    )
    for r in sorted(records, key=lambda x: (x["format"], x["sut"], x["rep"])):
        lines.append(
            f"| {r['sut']} | {r['format']} | {r['rep']} | "
            f"{r.get('exit_code', '—')} | {float(r.get('line_pct', 0)):.2f}% | "
            f"{r.get('covered', 0)}/{r.get('total', 0)} | "
            f"{r.get('elapsed_s', 0)} | {r.get('status', '?')} |"
        )

    out = args.out_root / "SUMMARY.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print()
    print("\n".join(lines[:12]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
