"""Phase 3 — Mutation score, Pure Random × every SUT driver.

Covers DESIGN.md §13.5 Phase 3 checkbox "Pure Random × every SUT
(6 cells; one PIT + two mutmut + two mull-or-cargo-mutants calls.
The floor-baseline's mutation score is the key comparator for the
other tools)". Emits per-cell `summary.json` files matching the
DESIGN.md §3.3 contract
(``{killed, reachable, score, mutator_count, mutant_count}``)
alongside a matrix-level summary.csv so the Phase-6 report
consumer reads a uniform shape.

Test-kill protocol (DESIGN §3.3) — per cell:

  1. Corpus = Pure Random's Phase-2 generated files (200 random
     files per rep × 3 reps union). Feeds the mutation tool as
     "test suite".
  2. Baseline: parse each file with the unmutated SUT, hash the
     record stream → {filename: fingerprint} JSON.
  3. Mutator loop: for each mutant generated by the per-language
     engine, re-run the corpus through the mutated SUT. If any
     fingerprint flips, the mutant is KILLED; otherwise SURVIVED.
  4. score = killed / reachable; reachable = killed + survived +
     timeout + suspicious (mutmut's standard definition — any
     mutant whose code was actually executed by the corpus).
  5. Emit `summary.json` and append a row to the matrix CSV.

Per-SUT mutation engine dispatch:

   | SUT         | Engine          | Notes                                 |
   |:------------|:----------------|:--------------------------------------|
   | htsjdk      | PIT             | Deferred — see DESIGN §13.5 Phase 3   |
   | vcfpy       | mutmut 3.x      | Uses vcfpy_corpus_runner.py fingerprint runner |
   | biopython   | mutmut 3.x      | Uses biopython_corpus_runner.py (new) |
   | seqan3      | mull            | Deferred — Clang 18 + mull on Linux only |
   | noodles-vcf | cargo-mutants   | Deferred — Rust toolchain absent on this host |

On the Windows dev host mutmut runs natively (installed via
``pip install mutmut==3.0.0``); PIT / mull / cargo-mutants are
NOT in scope here and each produces a blocked-matrix-slot entry
with a ``blocked_reason`` and the promotion command to re-run
inside ``biotest-bench:latest``. This mirrors the Phase-2
pure_random noodles-vcf handling — every cell is represented so
Phase-6 CI bands compare fairly across tools.

Usage:

    py -3.12 compares/scripts/run_pure_random_phase3.py \\
        --run-all --budget 7200

Or per-cell:

    py -3.12 compares/scripts/run_pure_random_phase3.py \\
        --sut vcfpy --budget 7200 \\
        --out compares/results/mutation/pure_random/vcfpy

Requires that Phase 2 has already run (reads the corpus from
``compares/results/coverage/pure_random/<cell>/run_*/corpus``).
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

logger = logging.getLogger("run_pure_random_phase3")

REPO_ROOT = Path(__file__).resolve().parents[2]
COVERAGE_ROOT = REPO_ROOT / "compares" / "results" / "coverage" / "pure_random"
MUTATION_ROOT = REPO_ROOT / "compares" / "results" / "mutation" / "pure_random"
RUNNER_DIR = REPO_ROOT / "compares" / "scripts" / "mutation"
VCFPY_RUNNER = RUNNER_DIR / "vcfpy_corpus_runner.py"
BIOPYTHON_RUNNER = RUNNER_DIR / "biopython_corpus_runner.py"

# ---------------------------------------------------------------------------
# Scope — mutation MUST match biotest_config.yaml:coverage.target_filters
# so the mutation score isn't diluted by code BioTest never exercises.
# DESIGN.md §3.3 "Scoping" + Flow.md §SUT Matrix both pin this.
# ---------------------------------------------------------------------------
#
# vcfpy (VCF): parser / reader / writer / header / record only.
#   EXCLUDED on purpose (Flow.md: "排除 bgzf/tabix —— BioTest 不走这些路径"):
#     * bgzf.py     — BGZF compression (BioTest tests plain .vcf, not .vcf.gz)
#     * tabix.py    — tabix indexing (no random-access tests)
#     * exceptions.py, compat.py — pure data classes / compat shims
#     * __init__.py is kept so `import vcfpy` still resolves the mutable copy
VCFPY_IN_SCOPE_FILES: tuple[str, ...] = (
    "__init__.py",  # required for package import
    "reader.py",
    "parser.py",
    "header.py",
    "record.py",
    "writer.py",
)

# biopython (SAM): Bio/Align/sam.py — a single module, inherently scoped.
# No allowlist needed; _find_biopython_sam_src() returns the single file.

# htsjdk / seqan3 / noodles — their engines (PIT / mull / cargo-mutants)
# accept scope flags directly and are blocked on the Windows host anyway;
# the promotion commands in _run_blocked_cell already carry the scope
# arguments per DESIGN.md §13.5 Phase 3 + compares/mutation/*/README.md.


# ---------------------------------------------------------------------------
# Corpus assembly
# ---------------------------------------------------------------------------

def _union_corpus(cell_name: str, out: Path) -> Path:
    """Merge the 3 Phase-2 reps' `run_*/corpus` directories under one
    tree so mutmut's corpus-runner sees a single stable root. Filename
    collisions resolve by keeping the first occurrence — with
    pure_random's deterministic RNG seeding (rep_idx → `0xB10 + i`),
    rep 0 already owns a unique prefix so the union is well-defined."""
    src = COVERAGE_ROOT / cell_name
    rep_dirs = sorted(src.glob("run_*/corpus"))
    if not rep_dirs:
        raise FileNotFoundError(
            f"Phase 2 corpus for cell {cell_name!r} not found "
            f"under {src}. Run Phase 2 first via "
            "`py -3.12 compares/scripts/run_pure_random_phase2.py "
            f"--run-all`."
        )
    dst = out / "union_corpus"
    dst.mkdir(parents=True, exist_ok=True)
    count = 0
    # Rename per-rep so collisions don't clobber content.
    for rep in rep_dirs:
        rep_label = rep.parent.name  # e.g. "run_0"
        for p in sorted(rep.iterdir()):
            if not p.is_file():
                continue
            tgt = dst / f"{rep_label}_{p.name}"
            if not tgt.exists():
                shutil.copy2(p, tgt)
                count += 1
    logger.info("union corpus for %s: %d files → %s", cell_name, count, dst)
    return dst


# ---------------------------------------------------------------------------
# mutmut dispatch (vcfpy + biopython)
# ---------------------------------------------------------------------------

def _copy_source_tree(
    module_init_or_file: Path, dst: Path,
    include_files: tuple[str, ...] | None = None,
) -> Path:
    """Copy an installed Python package/module into a mutable tree.

    * If `module_init_or_file` is a directory (package __init__.py's
      parent), copy the whole package — but if `include_files` is
      given, copy ONLY those filenames (plus the `__pycache__/` is
      never copied). This is how we enforce
      biotest_config.target_filters scope: vcfpy's mutation surface
      excludes `bgzf.py` + `tabix.py` + other off-path helpers so
      the Pure-Random mutation-score denominator reflects only what
      BioTest actually tests (DESIGN.md §3.3 Scoping; Flow.md SUT
      Matrix vcfpy row "排除 bgzf/tabix — BioTest 不走这些路径").
    * If it's a single module file (Bio/Align/sam.py), copy the file
      alone under dst — single file is inherently scoped.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        if dst.is_dir():
            shutil.rmtree(dst)
        else:
            dst.unlink()
    if module_init_or_file.is_dir():
        dst.mkdir(parents=True)
        if include_files is None:
            # No allowlist — copy the whole package (shouldn't normally
            # happen for SUTs with a defined target_filter scope).
            for p in module_init_or_file.iterdir():
                if p.is_file():
                    shutil.copy2(p, dst / p.name)
                elif p.is_dir() and p.name != "__pycache__":
                    shutil.copytree(p, dst / p.name)
        else:
            # Scope-aware copy: only the files BioTest actually exercises.
            for name in include_files:
                src_file = module_init_or_file / name
                if src_file.exists():
                    shutil.copy2(src_file, dst / name)
                else:
                    logger.warning(
                        "scope file %s missing in %s — skipped",
                        name, module_init_or_file,
                    )
        return dst
    # single file — create the wrapping dir
    dst.mkdir(parents=True)
    out_file = dst / module_init_or_file.name
    shutil.copy2(module_init_or_file, out_file)
    return out_file


def _find_vcfpy_src() -> Path:
    import vcfpy
    return Path(vcfpy.__file__).parent


def _find_biopython_sam_src() -> Path:
    from Bio.Align import sam
    return Path(sam.__file__)


BIOPYTHON_RUNNER_SRC = r'''"""Biopython Bio.Align.sam corpus-runner for mutmut (Phase-3 driver).

mutmut contract (``[tool.mutmut] runner = "<cmd>"``):
  * exit 0 → SURVIVED; exit 1 → KILLED; exit 33 → no tests.

This script plays the `pytest` role: replays a pure_random corpus
through the mutated `Bio.Align.sam.AlignmentIterator` and compares
fingerprints to a pre-mutation baseline.

Envs (set by mutation_driver):
  * MUTMUT_RUNNER_MODE        "baseline" or "check" (default "check")
  * MUTMUT_BIOPYTHON_SRC      path to mutable Bio/Align/sam.py
  * MUTMUT_CORPUS_DIR         directory of corpus files
  * MUTMUT_BASELINE_FILE      JSON {filename: fingerprint}
  * MUTMUT_CORPUS_SAMPLE      optional N (default 200)
  * MUTMUT_CORPUS_TIMEOUT_S   optional per-file timeout (default 2.0s)
"""

from __future__ import annotations

import hashlib
import json
import os
import signal
import sys
from pathlib import Path


def _ensure_src_on_path() -> None:
    src = os.environ.get("MUTMUT_BIOPYTHON_SRC")
    if not src:
        return
    pkg_file = Path(src).resolve()
    # If mutmut mutates Bio/Align/sam.py in place we need its parent
    # three levels up on sys.path so `from Bio.Align import sam` loads
    # our mutable copy. But dragging the whole Bio tree into the copy
    # is wasteful — instead, we replace the LIVE module's bytecode by
    # importing from the mutable file directly.
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "Bio.Align.sam", str(pkg_file),
    )
    if spec is None or spec.loader is None:
        return
    module = importlib.util.module_from_spec(spec)
    # Pre-import heavy deps so numpy's C ext loads before our swap.
    import numpy  # noqa: F401
    from Bio import Align  # noqa: F401 — parent package
    spec.loader.exec_module(module)
    sys.modules["Bio.Align.sam"] = module


class _TimeoutError(Exception):
    pass


def _alarm_handler(_signum, _frame):
    raise _TimeoutError("per-file parse exceeded MUTMUT_CORPUS_TIMEOUT_S")


def _sample_corpus_files(corpus_dir: Path, max_n: int) -> list[Path]:
    return sorted(p for p in corpus_dir.iterdir() if p.is_file())[:max_n]


def _fingerprint_for_file(path: Path, timeout_s: float) -> str:
    from Bio.Align import sam as _sam

    h = hashlib.sha1()
    if os.name == "posix":
        signal.signal(signal.SIGALRM, _alarm_handler)
        signal.setitimer(signal.ITIMER_REAL, timeout_s)
    try:
        try:
            with open(path) as fh:
                it = _sam.AlignmentIterator(fh)
                count = 0
                for rec in it:
                    count += 1
                    if count >= 200:
                        h.update(b"|cap")
                        break
                    try:
                        row = (
                            getattr(rec, "target", None),
                            getattr(rec, "query", None),
                            type(rec).__name__,
                        )
                        h.update(b"|r")
                        h.update(repr(row).encode(errors="replace"))
                    except BaseException as exc:
                        h.update(b"|r-fail:")
                        h.update(type(exc).__name__.encode())
                h.update(f"|n={count}".encode())
        except BaseException as exc:
            # Include a short exception-message fragment so header-reject
            # mutations that change the error text (same exception class,
            # different message) still flip the fingerprint. Without
            # this, pure-random's single-bucket corpus can't distinguish
            # most deep-parser mutations.
            msg = str(exc).replace("\n", " ")[:96]
            h.update(
                f"open-or-parse-fail:{type(exc).__name__}:{msg}".encode(
                    errors="replace",
                )
            )
    except _TimeoutError:
        return hashlib.sha1(b"timeout").hexdigest()
    finally:
        if os.name == "posix":
            signal.setitimer(signal.ITIMER_REAL, 0)
    return h.hexdigest()


def _run_baseline(corpus: Path, baseline: Path, n: int, to: float) -> int:
    _ensure_src_on_path()
    out = {p.name: _fingerprint_for_file(p, to)
           for p in _sample_corpus_files(corpus, n)}
    baseline.parent.mkdir(parents=True, exist_ok=True)
    baseline.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"[baseline] wrote {len(out)} entries to {baseline}")
    return 0


def _run_check(corpus: Path, baseline: Path, n: int, to: float) -> int:
    if not baseline.exists():
        print(f"[check] baseline missing: {baseline}", file=sys.stderr)
        return 33
    ref = json.loads(baseline.read_text(encoding="utf-8"))
    _ensure_src_on_path()
    for p in _sample_corpus_files(corpus, n):
        if p.name not in ref:
            continue
        fp = _fingerprint_for_file(p, to)
        if fp != ref[p.name]:
            print(f"[check] KILL {p.name}: base={ref[p.name][:12]} "
                  f"mut={fp[:12]}", file=sys.stderr)
            return 1
    return 0


def main() -> int:
    mode = os.environ.get("MUTMUT_RUNNER_MODE", "check").lower()
    corpus = Path(os.environ.get("MUTMUT_CORPUS_DIR", "")).resolve()
    baseline = Path(os.environ.get("MUTMUT_BASELINE_FILE", "")).resolve()
    n = int(os.environ.get("MUTMUT_CORPUS_SAMPLE", "200"))
    to = float(os.environ.get("MUTMUT_CORPUS_TIMEOUT_S", "2.0"))
    if not corpus.exists() or not corpus.is_dir():
        print(f"[runner] MUTMUT_CORPUS_DIR invalid: {corpus}", file=sys.stderr)
        return 2
    if mode == "baseline":
        return _run_baseline(corpus, baseline, n, to)
    return _run_check(corpus, baseline, n, to)


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _ensure_biopython_runner() -> Path:
    """Materialise the biopython corpus-runner next to the vcfpy one."""
    BIOPYTHON_RUNNER.parent.mkdir(parents=True, exist_ok=True)
    if not BIOPYTHON_RUNNER.exists():
        BIOPYTHON_RUNNER.write_text(BIOPYTHON_RUNNER_SRC, encoding="utf-8")
    return BIOPYTHON_RUNNER


def _run_mutmut_cell(
    sut: str,
    corpus_dir: Path,
    budget_s: int,
    out_dir: Path,
    src_path_finder,  # Callable[[], Path]
    runner_script: Path,
    src_env_var: str,
    mutate_dir_name: str,
    include_files: tuple[str, ...] | None = None,
    corpus_sample: int = 200,
) -> dict:
    """Shared mutmut cell for vcfpy / biopython.

    `include_files` enforces the biotest_config.target_filters scope
    at copy time — only files BioTest actually exercises get mutated,
    so the score denominator isn't padded with unreachable mutants in
    off-path helpers (bgzf, tabix, etc.)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    baseline_file = out_dir / "baseline.json"
    runner_log = out_dir / "runner.log"
    mutmut_log = out_dir / "mutmut_run.log"
    results_txt = out_dir / "mutmut_results.txt"
    summary_path = out_dir / "summary.json"

    # Materialise a mutable copy of the SUT source under `src/`. We
    # copy the WHOLE package so the import graph stays intact (vcfpy's
    # __init__.py pulls from vcfpy.exceptions / vcfpy.bgzf), but we
    # will restrict `--paths-to-mutate` to the in-scope files below so
    # mutmut only injects mutations into what BioTest exercises
    # (DESIGN §3.3 Scoping; Flow.md vcfpy row "排除 bgzf/tabix").
    src_src = src_path_finder()
    src_dst = _copy_source_tree(
        src_src, out_dir / "src" / mutate_dir_name,
        include_files=None,
    )

    # 1. Capture baseline fingerprints from the unmutated SUT.
    logger.info("[%s] capturing baseline → %s", sut, baseline_file)
    env = os.environ.copy()
    env.update({
        "MUTMUT_RUNNER_MODE": "baseline",
        src_env_var: str(src_dst.resolve()),
        "MUTMUT_CORPUS_DIR": str(corpus_dir.resolve()),
        "MUTMUT_BASELINE_FILE": str(baseline_file.resolve()),
        "MUTMUT_CORPUS_SAMPLE": str(corpus_sample),
        "MUTMUT_CORPUS_TIMEOUT_S": "2.0",
        "PYTHONUNBUFFERED": "1",
    })
    with runner_log.open("wb") as fh:
        rc = subprocess.run(
            [sys.executable, str(runner_script)],
            env=env, stdout=fh, stderr=fh,
            check=False, timeout=600,
        ).returncode
    if rc != 0 or not baseline_file.exists():
        return {
            "skipped": True,
            "blocked_reason": (
                f"baseline capture failed for {sut} (rc={rc}); "
                f"see {runner_log}"
            ),
        }
    baseline_entries = len(json.loads(
        baseline_file.read_text(encoding="utf-8"),
    ))
    logger.info("[%s] baseline entries: %d", sut, baseline_entries)

    # 2. mutmut 2.5 refuses to start unless a `tests/` dir exists (even
    #    though we pass a custom --runner that doesn't use pytest). Put
    #    a marker file so the directory scan succeeds; the runner ignores
    #    anything in tests/.
    (out_dir / "tests").mkdir(exist_ok=True)
    (out_dir / "tests" / ".keep").touch()

    # 3. Invoke `mutmut run` with CLI flags (mutmut 2.5.1 syntax).
    #    `--paths-to-mutate` is the BioTest-exercised scope — a
    #    comma-separated list of files if `include_files` is set, or
    #    the whole package directory otherwise. `--runner` is the
    #    per-mutant test suite (our fingerprint-compare driver).
    if include_files:
        # Scope to individual files: mutmut mutates only these.
        target_rel = ",".join(
            f"src/{mutate_dir_name}/{name}"
            for name in include_files
            if name != "__init__.py"  # don't mutate the package marker
        )
    else:
        target_rel = f"src/{mutate_dir_name}"
    # mutmut forwards `--runner` to shell execution, so it must be a
    # single string; use forward-slashes for Windows friendliness.
    runner_cmd = (
        f'"{sys.executable}" "{runner_script.resolve()}"'
    )
    env["MUTMUT_RUNNER_MODE"] = "check"
    # mutmut's progress renderer uses Braille spinner chars that cp1252
    # can't encode; force UTF-8 on the subprocess so the ASCII fallback
    # doesn't kick in mid-run with a UnicodeEncodeError.
    env["PYTHONIOENCODING"] = "utf-8"
    # Clean any prior .mutmut-cache so runs are deterministic (mutmut
    # 2.5.1 keeps cache in cwd; would otherwise resume partially-run
    # cells across script invocations). mutmut 2.5's cache is a single
    # SQLite file (not a directory) so use unlink().
    cache_file = out_dir / ".mutmut-cache"
    if cache_file.exists():
        try:
            if cache_file.is_file():
                cache_file.unlink()
            else:
                shutil.rmtree(cache_file, ignore_errors=True)
        except (OSError, PermissionError) as e:
            logger.warning(
                "[%s] could not clear .mutmut-cache (%s) — if this is a "
                "zombie lock, rename --out to a fresh dir for this run",
                sut, e,
            )
    start = time.time()
    with mutmut_log.open("wb") as fh:
        try:
            rc = subprocess.run(
                [
                    sys.executable, "-m", "mutmut", "run",
                    "--paths-to-mutate", target_rel,
                    "--runner", runner_cmd,
                    # `--CI` uniform exit codes; easier to parse.
                    "--CI",
                    # Quieter output — no Braille spinner.
                    "--simple-output",
                ],
                env=env, cwd=str(out_dir), stdout=fh, stderr=fh,
                check=False, timeout=budget_s,
            ).returncode
        except subprocess.TimeoutExpired:
            rc = -1
    dur = time.time() - start
    logger.info("[%s] mutmut run rc=%s in %.0fs", sut, rc, dur)

    # 4. `mutmut results` summary.
    with results_txt.open("wb") as fh:
        subprocess.run(
            [sys.executable, "-m", "mutmut", "results"],
            env=env, cwd=str(out_dir), stdout=fh, stderr=fh,
            check=False, timeout=120,
        )

    # 5. mutmut 2.5's `.mutmut-cache` is a SQLite file (not a directory).
    #    Back it up with copy2 for audit; leave original in place so
    #    `mutmut results` can still read it on a re-run. The cache is
    #    the authoritative source for killed/survived/suspicious counts
    #    (mutmut 2.5.1's text-mode `results` output hides the "killed"
    #    section — see _sqlite_status_counts below for the fix).
    cache_db = out_dir / ".mutmut-cache"
    cache_backup = out_dir / "mutmut_cache_backup.sqlite"
    if cache_db.exists() and cache_db.is_file():
        shutil.copy2(cache_db, cache_backup)

    # Prefer the SQLite cache (authoritative) over `mutmut results`
    # text (2.5.1 hides the "killed" section). Fall through to the
    # text parser if cache is missing.
    stats = _sqlite_status_counts(cache_backup)
    if stats is None:
        stats = _summarise_mutmut_output(results_txt, mutmut_log)
    stats.update({
        "tool": "pure_random",
        "sut": sut,
        "phase": "mutation",
        "engine": "mutmut 2.5",
        "time_budget_s": budget_s,
        "mutmut_exit_code": rc,
        "mutmut_duration_s": round(dur, 2),
        "baseline_entries": baseline_entries,
        "paths_to_mutate": [target_rel],
        "corpus_dir": str(corpus_dir),
    })
    summary_path.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    logger.info("[%s] wrote %s  killed=%d survived=%d score=%s",
                sut, summary_path, stats.get("killed", 0),
                stats.get("survived", 0), stats.get("score_display"))
    return stats


def _sqlite_status_counts(cache_sqlite: Path) -> dict | None:
    """Read mutant statuses directly from mutmut 2.5's SQLite cache.

    mutmut 2.5.1's `mutmut results` text output only lists non-killed
    mutants (survived / suspicious / timeout / skipped). The full
    killed count is only readable from the SQLite `.mutmut-cache`
    file's `Mutant.status` column. Values we see:

      * `ok_killed`       → killed
      * `bad_survived`    → survived
      * `ok_suspicious`   → suspicious (took 2x baseline time)
      * `bad_timeout`     → timeout (took 10x, counted as killed-ish
                             under "timeout" in standard tooling but
                             we keep as a distinct bucket)
      * `skipped`         → skipped (runner rc=3; don't count)
      * `unknown`         → untested (incomplete run)

    Returns a DESIGN §3.3-shaped dict or None if the file is missing."""
    if not cache_sqlite.exists():
        return None
    try:
        import sqlite3
        con = sqlite3.connect(str(cache_sqlite))
        rows = con.execute(
            "SELECT status, COUNT(*) FROM Mutant GROUP BY status"
        ).fetchall()
        con.close()
    except Exception as e:  # noqa: BLE001
        logger.warning("sqlite read %s failed: %s", cache_sqlite, e)
        return None
    raw: dict[str, int] = {status: int(n) for status, n in rows}
    killed = raw.get("ok_killed", 0)
    survived = raw.get("bad_survived", 0)
    timeout = raw.get("bad_timeout", 0)
    suspicious = raw.get("ok_suspicious", 0)
    skipped = raw.get("skipped", 0)
    not_checked = (
        raw.get("unknown", 0) + raw.get("not_checked", 0)
    )
    reachable = killed + survived + timeout + suspicious
    total = reachable + skipped + not_checked
    score = (killed / reachable) if reachable else 0.0
    return {
        "killed": killed,
        "survived": survived,
        "timeout": timeout,
        "suspicious": suspicious,
        "skipped": skipped,
        "no_tests": 0,
        "not_checked": not_checked,
        "reachable": reachable,
        "mutant_count": total,
        "score": round(score, 4),
        "score_display": (
            f"{score * 100:.2f}%" if reachable else "n/a (reachable=0)"
        ),
        "raw_status_counts": raw,
    }


def _summarise_mutmut_output(results_txt: Path, log_file: Path) -> dict:
    """Parse the ``mutmut results`` printout into numbers.

    mutmut 2.5 prints category headers like:
        Killed 🎉 (42)
        Survived 🙁 (1255)
        Timeout ⏰ (1)
        Suspicious 🤔 (0)
        Skipped 🔇 (0)
        Untested/skipped (984)
    We extract the bracketed counts and compute DESIGN §3.3:
        reachable = killed + survived + timeout + suspicious
        score     = killed / reachable
    'Untested/skipped' mutants are treated as unreachable (mutmut's
    equivalent of 'mutant function never executed by the runner')."""
    status_counts: dict[str, int] = {}
    text = ""
    if results_txt.exists():
        text = results_txt.read_text(encoding="utf-8", errors="replace")
    if not text and log_file.exists():
        text = log_file.read_text(encoding="utf-8", errors="replace")
    # mutmut 2.x "Category (N)" header, possibly with emoji in between.
    import re
    header_re = re.compile(
        r"^(Killed|Survived|Timeout|Suspicious|Skipped|Untested[/ ]skipped)"
        r"[^\(]*\((\d+)\)",
        re.IGNORECASE | re.MULTILINE,
    )
    for m in header_re.finditer(text):
        key = m.group(1).lower().replace("/skipped", "").replace(" ", "_")
        # "Untested" alone maps to our `not_checked` bucket.
        if key == "untested":
            key = "not_checked"
        status_counts[key] = int(m.group(2))
    # Also support the mutmut 3.x `killed: 42` form for forward-compat.
    known = {
        "killed", "survived", "timeout", "suspicious",
        "skipped", "no tests", "not checked",
    }
    for line in text.splitlines():
        s = line.strip()
        if ":" not in s:
            continue
        key, _, val = s.partition(":")
        key = key.strip().lower()
        val = val.strip().split()[0] if val.strip() else ""
        if key in known and val.isdigit():
            status_counts.setdefault(key.replace(" ", "_"), int(val))
    killed = status_counts.get("killed", 0)
    survived = status_counts.get("survived", 0)
    timeout = status_counts.get("timeout", 0)
    suspicious = status_counts.get("suspicious", 0)
    skipped = status_counts.get("skipped", 0)
    no_tests = status_counts.get("no_tests", 0)
    not_checked = status_counts.get("not_checked", 0)
    reachable = killed + survived + timeout + suspicious
    total = reachable + skipped + no_tests + not_checked
    score = (killed / reachable) if reachable else 0.0
    return {
        "killed": killed,
        "survived": survived,
        "timeout": timeout,
        "suspicious": suspicious,
        "skipped": skipped,
        "no_tests": no_tests,
        "not_checked": not_checked,
        "reachable": reachable,
        "mutant_count": total,
        "score": round(score, 4),
        "score_display": (
            f"{score * 100:.2f}%" if reachable else "n/a (reachable=0)"
        ),
        "raw_status_counts": status_counts,
    }


# ---------------------------------------------------------------------------
# PIT (htsjdk) — Java bytecode mutation via pitest 1.15.3
# ---------------------------------------------------------------------------
#
# Runs PIT against htsjdk classes using the CorpusReplayTest JUnit 5 test
# that iterates every file in `biotest.corpus` through VCFFileReader or
# SamReaderFactory. The test swallows exceptions by design — PIT uses
# JaCoCo-style coverage + assertion reachability to infer kill/survive.
#
# Mutation scope matches DESIGN §3.3 + biotest_config target_filters:
#   VCF → htsjdk.variant.vcf.* + htsjdk.variant.variantcontext.*
#   SAM → htsjdk.samtools.*
# Exclusions (JEXL filter-expression engine, BCF2 binary codec) are
# handled by PIT's --excludedClasses flag so the denominator matches the
# mutmut vcfpy row's "BioTest-exercised only" principle.

PIT_DIR = REPO_ROOT / "compares" / "baselines" / "pit"
PIT_JARS = [
    PIT_DIR / "pitest-command-line-1.15.3.jar",
    PIT_DIR / "pitest-1.15.3.jar",
    PIT_DIR / "pitest-entry-1.15.3.jar",
    PIT_DIR / "pitest-junit5-plugin-1.2.1.jar",
    PIT_DIR / "commons-text-1.10.0.jar",
    PIT_DIR / "commons-lang3-3.14.0.jar",
]
JUNIT_JAR = (
    REPO_ROOT / "compares" / "baselines" / "junit"
    / "junit-platform-console-standalone-1.10.1.jar"
)
HTSJDK_FATJAR = (
    REPO_ROOT / "harnesses" / "java" / "build" / "libs"
    / "biotest-harness-all.jar"
)
PIT_TEST_CLASSES_DIR = (
    REPO_ROOT / "compares" / "harnesses" / "pit" / "classes"
)
PIT_HTSJDK_CLASSES_DIR = (
    REPO_ROOT / "compares" / "harnesses" / "pit" / "htsjdk-classes"
)
PIT_TEST_SRC_DIR = REPO_ROOT / "compares" / "harnesses" / "pit"

PIT_FORMAT_CONFIG: dict[str, tuple[str, str]] = {
    # (targetClasses, targetTests method)
    "VCF": (
        "htsjdk.variant.vcf.*,htsjdk.variant.variantcontext.*",
        "CorpusReplayTest#replayVcfCorpus",
    ),
    "SAM": (
        "htsjdk.samtools.*",
        "CorpusReplayTest#replaySamCorpus",
    ),
}
# JEXL and BCF2 are explicitly out of scope (§3.3) — mutants there would
# always survive against a pure-random VCF/SAM corpus. The NCBI SRA /
# NGS classes are also excluded: htsjdk bundles thin wrappers around
# `ngs/Alignment` which we don't redistribute, so PIT's bytecode
# analyzer trips on ClassNotFoundException.
PIT_EXCLUDED_CLASSES = (
    "*JEXL*,*Jexl*,"
    "htsjdk.variant.bcf2.*,"
    "htsjdk.variant.vcf.VCF*Encoder,"
    "htsjdk.samtools.sra.*,"
    "htsjdk.samtools.cram.*,"
    "htsjdk.samtools.SRA*"
)


def _ensure_pit_htsjdk_classes() -> None:
    """Extract htsjdk/*.class from the fatjar to a flat directory so PIT's
    coverage analyzer (which can't descend into nested jars) sees them.
    Idempotent — skips if the marker class is already on disk."""
    marker = PIT_HTSJDK_CLASSES_DIR / "htsjdk" / "variant" / "vcf" / "VCFCodec.class"
    if marker.exists():
        return
    PIT_HTSJDK_CLASSES_DIR.mkdir(parents=True, exist_ok=True)
    import zipfile
    with zipfile.ZipFile(str(HTSJDK_FATJAR)) as zf:
        for name in zf.namelist():
            if name.startswith("htsjdk/") and name.endswith(".class"):
                target = PIT_HTSJDK_CLASSES_DIR / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(zf.read(name))


def _run_pit_cell(
    fmt: str,
    corpus_dir: Path,
    budget_s: int,
    out_dir: Path,
) -> dict:
    """Invoke PIT against htsjdk for the given format. Returns a summary
    dict shaped like the mutmut cells: `{killed, survived, timeout,
    suspicious, not_checked, reachable, score, ...}`."""
    import xml.etree.ElementTree as _ET

    out_dir.mkdir(parents=True, exist_ok=True)
    report_dir = out_dir / "pit_report"
    if report_dir.exists():
        shutil.rmtree(report_dir, ignore_errors=True)

    target_classes, target_tests = PIT_FORMAT_CONFIG[fmt]
    # Classpath for PIT main + test + htsjdk + deps.
    cp_entries = [
        *[str(j.resolve()) for j in PIT_JARS],
        str(PIT_TEST_CLASSES_DIR.resolve()),
        str(PIT_HTSJDK_CLASSES_DIR.resolve()),
        str(JUNIT_JAR.resolve()),
    ]
    cp = os.pathsep.join(cp_entries)

    cmd = [
        "java",
        f"-Dbiotest.corpus={corpus_dir.resolve()}",
        "-cp", cp,
        "org.pitest.mutationtest.commandline.MutationCoverageReport",
        "--reportDir", str(report_dir.resolve()),
        "--targetClasses", target_classes,
        "--excludedClasses", PIT_EXCLUDED_CLASSES,
        "--targetTests", target_tests.split("#")[0],
        "--sourceDirs", str(PIT_TEST_SRC_DIR.resolve()),
        "--outputFormats", "XML",
        "--threads", "1",
        "--mutators", "DEFAULTS",
        "--timeoutConst", "8000",
        "--timeoutFactor", "1.5",
        "--verbose", "false",
    ]
    run_log = out_dir / "pit_run.log"
    start = time.time()
    with run_log.open("wb") as fh:
        try:
            rc = subprocess.run(
                cmd, stdout=fh, stderr=fh,
                timeout=budget_s, check=False,
            ).returncode
        except subprocess.TimeoutExpired:
            rc = -1
    dur = time.time() - start

    mutations_xml = report_dir / "mutations.xml"
    killed = survived = timeout = suspicious = not_checked = 0
    if mutations_xml.exists():
        try:
            tree = _ET.parse(str(mutations_xml))
            for m in tree.getroot().findall("mutation"):
                status = (m.get("status") or "").upper()
                if status == "KILLED":
                    killed += 1
                elif status == "SURVIVED":
                    survived += 1
                elif status == "TIMED_OUT":
                    timeout += 1
                elif status == "RUN_ERROR":
                    suspicious += 1
                elif status == "NO_COVERAGE":
                    # Matches mutmut's "not_checked / unreachable" bucket.
                    not_checked += 1
                elif status == "NON_VIABLE":
                    # Mutation itself was invalid — exclude from
                    # denominator.
                    not_checked += 1
                else:
                    not_checked += 1
        except Exception as e:  # noqa: BLE001
            logger.warning("parse PIT XML failed: %s", e)

    reachable = killed + survived + timeout + suspicious
    total = reachable + not_checked
    score = (killed / reachable) if reachable else 0.0
    payload = {
        "tool": "pure_random",
        "sut": f"htsjdk_{fmt.lower()}",
        "phase": "mutation",
        "engine": "PIT 1.15.3",
        "time_budget_s": budget_s,
        "killed": killed,
        "survived": survived,
        "timeout": timeout,
        "suspicious": suspicious,
        "skipped": 0,
        "no_tests": 0,
        "not_checked": not_checked,
        "reachable": reachable,
        "mutant_count": total,
        "score": round(score, 4),
        "score_display": (
            f"{score * 100:.2f}%" if reachable else "n/a (reachable=0)"
        ),
        "pit_duration_s": round(dur, 2),
        "pit_exit_code": rc,
        "corpus_dir": str(corpus_dir.resolve()),
        "target_classes": target_classes,
        "target_tests": target_tests,
        "mutations_xml": str(mutations_xml.resolve()),
    }
    (out_dir / "summary.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8",
    )
    logger.info(
        "[htsjdk_%s] PIT rc=%s dur=%.0fs killed=%d survived=%d "
        "reachable=%d score=%s",
        fmt.lower(), rc, dur, killed, survived, reachable,
        payload["score_display"],
    )
    return payload


# ---------------------------------------------------------------------------
# Blocked-cell handler (noodles / seqan3 — still blocked if tools absent)
# ---------------------------------------------------------------------------

def _run_blocked_cell(
    sut: str,
    engine: str,
    reason: str,
    promote_cmd: str,
    corpus_dir: Path | None,
    budget_s: int,
    out_dir: Path,
) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "tool": "pure_random",
        "sut": sut,
        "phase": "mutation",
        "engine": engine,
        "time_budget_s": budget_s,
        "killed": 0,
        "survived": 0,
        "timeout": 0,
        "suspicious": 0,
        "skipped": 0,
        "no_tests": 0,
        "not_checked": 0,
        "reachable": 0,
        "mutant_count": 0,
        "score": 0.0,
        "score_display": "blocked",
        "blocked_reason": reason,
        "promotion_command": promote_cmd,
        "note": (
            "mutation_growth fields are 0 for this cell — see "
            "blocked_reason. Matrix slot preserved so Phase-6 "
            "comparisons stay complete across tools; rerun inside "
            "biotest-bench Docker image to promote to real numbers."
        ),
        "corpus_dir": str(corpus_dir) if corpus_dir else "",
    }
    (out_dir / "summary.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8",
    )
    logger.info("[%s] blocked: %s", sut, reason[:80])
    return payload


# ---------------------------------------------------------------------------
# Matrix driver
# ---------------------------------------------------------------------------

def run_cell(
    sut: str, budget_s: int, out_root: Path,
    corpus_override: Path | None = None,
    corpus_sample: int = 200,
) -> dict:
    """Dispatch to the per-SUT engine. Returns the per-cell summary dict.

    `corpus_override` lets callers supply a caller-provided corpus
    directory instead of auto-unioning the 3 Phase-2 reps. Used by
    the 4-run aggregation (each run wants a distinct fresh corpus
    so mutmut results vary across runs)."""
    out_dir = out_root / sut
    corpus_source_cell = {
        "htsjdk_vcf": "htsjdk_vcf",
        "htsjdk_sam": "htsjdk_sam",
        "vcfpy": "vcfpy",
        "noodles": "noodles",
        "biopython": "biopython",
        "seqan3": "seqan3",
    }[sut]
    if corpus_override is not None:
        if not corpus_override.is_dir():
            raise FileNotFoundError(
                f"--corpus-override path not a directory: {corpus_override}"
            )
        corpus_dir = corpus_override
        logger.info("[%s] using corpus override: %s", sut, corpus_dir)
    else:
        try:
            corpus_dir = _union_corpus(corpus_source_cell, out_dir)
        except FileNotFoundError as e:
            logger.warning("%s — %s", sut, e)
            corpus_dir = None

    if sut == "vcfpy":
        return _run_mutmut_cell(
            sut="vcfpy",
            corpus_dir=corpus_dir,
            budget_s=budget_s,
            out_dir=out_dir,
            src_path_finder=_find_vcfpy_src,
            runner_script=VCFPY_RUNNER,
            src_env_var="MUTMUT_VCFPY_SRC",
            # Must match the actual importable package name so the
            # corpus-runner's `import vcfpy` resolves to the mutable
            # copy rather than the venv site-packages.
            mutate_dir_name="vcfpy",
            # biotest_config target_filter: only what BioTest drives.
            include_files=VCFPY_IN_SCOPE_FILES,
            corpus_sample=corpus_sample,
        )
    if sut == "biopython":
        _ensure_biopython_runner()
        return _run_mutmut_cell(
            sut="biopython",
            corpus_dir=corpus_dir,
            budget_s=budget_s,
            out_dir=out_dir,
            src_path_finder=_find_biopython_sam_src,
            runner_script=BIOPYTHON_RUNNER,
            src_env_var="MUTMUT_BIOPYTHON_SRC",
            # single-file module — any name works; pick something
            # distinct so the biopython runner's importlib path is
            # unambiguous.
            mutate_dir_name="biopython_sam",
            corpus_sample=corpus_sample,
        )
    if sut in ("htsjdk_vcf", "htsjdk_sam"):
        fmt = "VCF" if sut == "htsjdk_vcf" else "SAM"
        # Unblocked 2026-04-22 — PIT 1.15.3 runs natively on the
        # Windows host now that the JUnit 5 wrapper + compiled
        # classpath are checked in under compares/harnesses/pit/.
        if corpus_dir is None or not corpus_dir.is_dir():
            return _run_blocked_cell(
                sut, "PIT 1.15.3",
                f"corpus directory missing: {corpus_dir}",
                "", corpus_dir, budget_s, out_dir,
            )
        # PIT runs on classfiles, not nested-jar entries — make sure the
        # extracted htsjdk class tree exists (idempotent).
        _ensure_pit_htsjdk_classes()
        return _run_pit_cell(fmt, corpus_dir, budget_s, out_dir)
    if sut == "noodles":
        reason = (
            "cargo-mutants (Rust) requires the Rust toolchain (cargo + "
            "rustc), which is absent on this Windows dev host. "
            "Dockerfile.bench bakes the toolchain and cargo-mutants is "
            "queued for install — run inside biotest-bench."
        )
        promote = (
            "# Inside biotest-bench container:\n"
            "python3.12 compares/scripts/mutation_driver.py "
            "--tool pure_random --sut noodles "
            "--corpus compares/results/mutation/pure_random/noodles/union_corpus "
            "--budget 7200 "
            "--out compares/results/mutation/pure_random/noodles/"
        )
        return _run_blocked_cell("noodles", "cargo-mutants", reason,
                                 promote, corpus_dir, budget_s, out_dir)
    if sut == "seqan3":
        reason = (
            "mull (C++ LLVM IR mutation) requires Clang 18 + mull 0.33 "
            "LLVM-18 runtime, which are only available inside "
            "biotest-bench Docker image (DESIGN §13.2.4 + §13.3.3). Not "
            "reproducible on the Windows/MSYS2 host."
        )
        promote = (
            "# Inside biotest-bench container:\n"
            "python3.12 compares/scripts/mutation_driver.py "
            "--tool pure_random --sut seqan3 "
            "--corpus compares/results/mutation/pure_random/seqan3/union_corpus "
            "--budget 7200 "
            "--out compares/results/mutation/pure_random/seqan3/"
        )
        return _run_blocked_cell("seqan3", "mull 0.33 (LLVM 18)",
                                 reason, promote, corpus_dir, budget_s, out_dir)
    raise ValueError(f"unsupported sut: {sut!r}")


MATRIX = (
    "htsjdk_vcf", "htsjdk_sam", "vcfpy", "noodles", "biopython", "seqan3",
)


def _write_summary_csv(rows: list[dict], out: Path) -> None:
    cols = [
        "sut", "engine", "time_budget_s", "killed", "survived",
        "timeout", "suspicious", "skipped", "no_tests", "not_checked",
        "reachable", "mutant_count", "score", "score_display",
        "blocked_reason",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in cols})


def _cli() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--sut", choices=list(MATRIX),
                   help="single SUT cell (or use --run-all)")
    p.add_argument("--budget", type=int, default=7200)
    p.add_argument("--out", type=Path, default=None,
                   help="override cell output dir (single-cell only)")
    p.add_argument("--run-all", action="store_true",
                   help="iterate all 6 DESIGN §13.5 Phase-3 Pure Random cells")
    p.add_argument("--out-root", type=Path, default=None,
                   help="override the matrix output root "
                        "(default: compares/results/mutation/pure_random/)")
    p.add_argument("--corpus-override", type=Path, default=None,
                   help="supply a caller-provided corpus directory instead "
                        "of auto-unioning the Phase-2 reps. Used by the "
                        "4-run aggregation where each run wants a fresh "
                        "corpus for variance across mutmut passes.")
    p.add_argument("--corpus-sample", type=int, default=200,
                   help="max files per mutant replay (smaller → faster "
                        "mutmut run with slightly noisier score). "
                        "Default 200 matches the Phase-3 first-run "
                        "baseline; 50 is a reasonable fast-regime for "
                        "re-runs in the 4-run aggregation.")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    if not args.run_all and not args.sut:
        print("Need --run-all or --sut <name>", file=sys.stderr)
        return 2

    cells = list(MATRIX) if args.run_all else [args.sut]
    rows: list[dict] = []
    matrix_out_root = args.out_root or MUTATION_ROOT
    for sut in cells:
        out_root = (args.out.parent if args.out is not None
                    else matrix_out_root)
        try:
            stats = run_cell(
                sut, args.budget, out_root,
                corpus_override=args.corpus_override,
                corpus_sample=args.corpus_sample,
            )
        except Exception as e:  # noqa: BLE001
            logger.exception("cell %s failed", sut)
            stats = {
                "tool": "pure_random", "sut": sut, "phase": "mutation",
                "killed": 0, "reachable": 0, "score": 0.0,
                "score_display": "error", "blocked_reason": repr(e),
            }
        rows.append(stats)

    _write_summary_csv(rows, matrix_out_root / "summary.csv")
    print()
    print(f"{'sut':<14}{'engine':<22}{'killed':>8}{'reachable':>12}"
          f"{'score':>10}  {'status':<30}")
    print("-" * 100)
    for r in rows:
        eng = r.get("engine") or ("blocked" if r.get("blocked_reason") else "mutmut 2.5")
        status = (r.get("blocked_reason") or "ok")[:30]
        sut_label = r.get("sut", "?")
        print(f"{sut_label:<14}{eng:<22}"
              f"{r.get('killed',0):>8}{r.get('reachable',0):>12}"
              f"{(r.get('score_display','') or 'n/a'):>10}  {status:<30}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
