"""Fresh-baseline mutation run — externally-sourced seeds ONLY.

Motivation: the Run-8 multi-rep numbers were computed against a corpus
produced by BioTest's own MR/synth/Rank pipeline. To establish a
*fair-against-other-tools* baseline, this script reruns the mutation
score using **only seeds that were not generated by BioTest** — files
that came from external test suites, real-world examples, or other
tools' provided corpora.

Inclusion (KEEP):
- `bcftools_*`     — bcftools regression tests
- `htsjdk_*`       — htsjdk's own test resources
- `real_world_*`   — real-world VCF/SAM curated from upstream tools
- `spec_*`         — VCF/SAM spec examples
- `jazzer_*`       — jazzer-baseline-provided SAM corpus (external)
- `minimal_*`,
  `complex_*`      — hand-crafted spec-shaped examples (treated as
                     curated test data, same provenance class as spec_*)
- non-prefixed     — small named files like `complex_cigar.sam`,
                     `clip_h.sam` — hand-curated spec inputs

Exclusion (SKIP — anything BioTest generated):
- `kept_*`         — Rank 8 corpus keeper (from MR loop)
- `synthetic_*`    — Phase-D LLM-synthesised
- `struct_*`       — Rank 12 structural diversifier
- `diverse_*`      — Rank 9 value diversifier
- `bytefuzz_*`     — Rank 10 byte fuzzer
- `bv_*`           — Rank 11 boundary-value generator
- `rawfuzz_*`      — Rank 13 lenient byte fuzzer

This corpus is deterministic by construction (no Rank 13 stochastic
layer included), so 1 rep per cell is sufficient — variance across
reps would be exactly 0. The result is reported as a single
measurement per cell, against the same DESIGN §3.3 formula and the
same mutation engine the baselines use.
"""
from __future__ import annotations

import json
import os
import shutil
import statistics
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
os.chdir(REPO_ROOT)

# Same 6 cells as Run-8.
CELLS = [
    ("htsjdk_vcf", "htsjdk",    "VCF", "pit"),
    ("htsjdk_sam", "htsjdk",    "SAM", "pit"),
    ("vcfpy",      "vcfpy",     "VCF", "mutmut"),
    ("noodles",    "noodles",   "VCF", "cargo_mutants"),
    ("biopython",  "biopython", "SAM", "atheris_mutmut"),
    ("seqan3_sam", "seqan3",    "SAM", "libfuzzer"),
]

# File-prefix policy. KEEP = externally sourced; SKIP = BioTest-generated.
EXTERNAL_PREFIXES = ("bcftools_", "htsjdk_", "real_world_", "spec_",
                     "jazzer_", "minimal_", "complex_", "clip_",
                     "mixed", "identity")
TOOL_GENERATED_PREFIXES = ("kept_", "synthetic_", "struct_", "diverse_",
                            "bytefuzz_", "bv_", "rawfuzz_")


def log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def is_external(name: str) -> bool:
    """Return True if a seed filename was sourced externally."""
    if any(name.startswith(p) for p in TOOL_GENERATED_PREFIXES):
        return False
    if any(name.startswith(p) for p in EXTERNAL_PREFIXES):
        return True
    # Anything else (small named files like complex_cigar.sam,
    # clip_h.sam) — treat as hand-curated spec input.
    return True


def stage_external_corpus(cell: str, fmt: str) -> Path:
    """Stage external-only corpus into compares/results/coverage/biotest_fresh/.../corpus."""
    rep_root = REPO_ROOT / f"compares/results/coverage/biotest_fresh/{cell}/run_0/corpus"
    rep_root.mkdir(parents=True, exist_ok=True)
    for existing in rep_root.glob("*"):
        if existing.is_file():
            existing.unlink()

    ext = fmt.lower()
    seed_dir = REPO_ROOT / f"seeds/{ext}"
    copied = []
    for f in sorted(seed_dir.glob(f"*.{ext}")):
        if is_external(f.name):
            shutil.copy2(f, rep_root / f.name)
            copied.append(f.name)
    log(f"  {cell}: {len(copied)} external {fmt} seeds staged → {rep_root.name}/")
    return rep_root


def launch_cell(cell: str, sut: str, fmt: str, engine: str) -> subprocess.Popen:
    """Launch mutation run for one cell (Run-8 launcher pattern)."""
    corpus = REPO_ROOT / f"compares/results/coverage/biotest_fresh/{cell}/run_0/corpus"
    out = REPO_ROOT / f"compares/results/mutation/biotest_fresh/{cell}"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)

    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    log_file = out / "driver.log"
    log_fp = open(log_file, "w", encoding="utf-8")

    if engine == "pit":
        ctr_name = f"fresh-{cell}"
        subprocess.run(["docker", "rm", "-f", ctr_name],
                       capture_output=True, check=False)
        cmd = [
            "docker", "run", "--rm", "--name", ctr_name,
            "-v", f"{REPO_ROOT}:/work", "-w", "/work",
            "-e", "TOOL=biotest_fresh",
            "-e", f"FORMATS={fmt}",
            "-e", "THREADS=2",
            "-e", "CORPUS_MAX=300",
            "-e", "REPS=0",
            "biotest-bench:latest",
            "bash", "/work/compares/scripts/phase3_jazzer_pit.sh",
        ]
        env["MSYS_NO_PATHCONV"] = "1"
    elif engine == "mutmut":
        cmd = ["py", "-3.12", "compares/scripts/mutation_driver.py",
               "--tool", "biotest", "--sut", "vcfpy",
               "--corpus", str(corpus), "--out", str(out),
               "--budget", "3600", "--corpus-sample", "80"]
    elif engine == "cargo_mutants":
        cmd = ["py", "-3.12", "compares/scripts/mutation_driver.py",
               "--tool", "biotest", "--sut", "noodles",
               "--corpus", str(corpus), "--out", str(out),
               "--budget", "7200", "--corpus-sample", "120"]
    elif engine == "atheris_mutmut":
        cmd = [
            "bash", "-c",
            f"TOOL=biotest_fresh BUDGET_S=1800 "
            f"bash compares/scripts/phase3_atheris_biopython.sh",
        ]
    elif engine == "libfuzzer":
        cmd = ["py", "-3.12", "compares/scripts/mutation_driver.py",
               "--tool", "biotest", "--sut", "seqan3",
               "--corpus", str(corpus), "--out", str(out),
               "--format", "SAM", "--budget", "7200", "--corpus-sample", "120"]
    else:
        raise ValueError(f"unknown engine {engine}")

    log(f"  launch {cell} [{engine}]: {' '.join(cmd[:4])}…")
    proc = subprocess.Popen(cmd, env=env, stdout=log_fp, stderr=log_fp)
    proc._biotest_log_fp = log_fp
    return proc


def read_summary(cell: str) -> dict | None:
    """Read summary.json for biotest_fresh/<cell>/."""
    out = REPO_ROOT / f"compares/results/mutation/biotest_fresh/{cell}"
    summary = out / "summary.json"
    if not summary.exists():
        return None
    if cell == "vcfpy":
        d = json.loads(summary.read_text(encoding="utf-8"))
        if d.get("killed", 0) == 0:
            subprocess.run([
                "py", "-3.12",
                "compares/scripts/mutation/rederive_from_meta.py",
                str(out), "--package", "vcfpy",
            ], check=False, capture_output=True)
    d = json.loads(summary.read_text(encoding="utf-8"))
    ms = d.get("mutation_score", d)
    killed = ms.get("killed", d.get("killed", 0))
    reachable = ms.get("reachable", d.get("reachable", 0))
    if reachable == 0:
        return None
    return {
        "killed": killed,
        "reachable": reachable,
        "score": killed / reachable,
    }


def write_report(results: dict, corpus_sizes: dict) -> None:
    """Write the fresh-baseline report."""
    baselines = {
        "htsjdk_vcf": ("Jazzer (n=4)", 36.15, 1.86),
        "htsjdk_sam": ("Jazzer (n=2)", 23.53, 0.41),
        "vcfpy":       ("Atheris (n=4)", 88.10, 2.18),
        "noodles":     ("cargo-fuzz (n=4)", 9.53, 0.33),
        "biopython":   ("Atheris (n=4 scoped)", 58.00, 0.36),
        "seqan3_sam":  ("libFuzzer (n=3)", 90.57, 0.00),
    }
    rank8_baseline = {
        # Run-8 BioTest mean ± std with full Rank 1-13 corpus
        "htsjdk_vcf": (31.51, 0.29),
        "htsjdk_sam": (22.63, 0.10),
        "vcfpy":       (85.89, 0.00),
        "noodles":     (8.36, 0.00),
        "biopython":   (25.24, 0.00),
        "seqan3_sam":  (98.08, 1.28),
    }
    pure_random = {
        "htsjdk_vcf": (0.00, 0.00),
        "htsjdk_sam": (1.20, 0.06),
        "vcfpy":       (0.89, 0.10),
        "noodles":     (0.00, 0.00),
        "biopython":   (0.24, 0.47),
        "seqan3_sam":  (7.19, 0.57),
    }

    lines = [
        "# BioTest Run-9 — Fresh-baseline mutation score (external seeds only)",
        "",
        "Single-rep deterministic measurement using **only externally-sourced",
        "seeds** — every BioTest-generated file (`kept_`, `synthetic_`,",
        "`struct_`, `diverse_`, `bytefuzz_`, `bv_`, `rawfuzz_`) is excluded.",
        "Result is the mutation score BioTest produces *without any of its",
        "own corpus-generation work* — analogous to running a baseline tool",
        "on its raw seed corpus before fuzzing.",
        "",
        "Variance is 0 by construction (deterministic corpus); reported as",
        "a single point estimate per cell.",
        "",
        "## 1. Headline — fresh vs full vs strongest baseline",
        "",
        "| cell | corpus size | **BioTest fresh (external only)** | BioTest Run-8 (full) | best baseline | floor (Pure Random) |",
        "| :--- | -----------: | -------------------------------: | -------------------: | :------------ | ------------------: |",
    ]
    for cell, sut, fmt, engine in CELLS:
        size = corpus_sizes.get(cell, 0)
        r = results.get(cell)
        if r is None:
            fresh_str = "MISSING"
        else:
            fresh_str = f"{r['killed']}/{r['reachable']} = {r['score']*100:.2f}%"
        run8_mean, run8_std = rank8_baseline[cell]
        run8_str = f"{run8_mean:.2f}% ± {run8_std:.2f}"
        bl_name, bl_mean, bl_std = baselines[cell]
        bl_str = f"{bl_name}: {bl_mean:.2f}% ± {bl_std:.2f}"
        pr_mean, pr_std = pure_random[cell]
        pr_str = f"{pr_mean:.2f}% ± {pr_std:.2f}"
        lines.append(
            f"| `{cell}` | {size} | **{fresh_str}** | {run8_str} | {bl_str} | {pr_str} |"
        )

    lines += [
        "",
        "## 2. Δ analysis",
        "",
        "| cell | fresh score | Δ vs Run-8 (full) | Δ vs best baseline | Δ vs Pure Random |",
        "| :--- | ----------: | ----------------: | -----------------: | ---------------: |",
    ]
    for cell, _, _, _ in CELLS:
        r = results.get(cell)
        if r is None:
            continue
        fresh = r["score"] * 100
        d_full = fresh - rank8_baseline[cell][0]
        d_baseline = fresh - baselines[cell][1]
        d_pr = fresh - pure_random[cell][0]
        lines.append(
            f"| `{cell}` | {fresh:.2f}% "
            f"| {d_full:+.2f}pp "
            f"| {d_baseline:+.2f}pp "
            f"| {d_pr:+.2f}pp |"
        )

    lines += [
        "",
        "## 3. What this measures",
        "",
        "- Same mutation engine as the baselines (PIT for htsjdk, mutmut",
        "  for vcfpy/biopython, cargo-mutants for noodles, mull-style",
        "  for seqan3).",
        "- Same DESIGN §3.3 formula `killed / reachable`.",
        "- Same target-class scope.",
        "- **Different corpus**: external curated seeds only, no Rank 8–13",
        "  augmentation, no Phase-C MR-grown files, no Phase-D LLM-synth.",
        "",
        "This isolates the *raw* mutation-killing power of the externally-",
        "sourced seeds when fed through BioTest's same-as-baseline mutation",
        "harness. The Δ vs Run-8 (full) column quantifies how much of",
        "BioTest's full-pipeline score comes from the Rank 8-13 augmentation",
        "vs. the underlying external corpus.",
        "",
        "## 4. Corpus sources (per cell)",
        "",
    ]
    for cell, sut, fmt, engine in CELLS:
        ext = fmt.lower()
        seed_dir = REPO_ROOT / f"seeds/{ext}"
        per_prefix = {}
        for f in seed_dir.glob(f"*.{ext}"):
            if is_external(f.name):
                # Take the first underscore-separated token
                pfx = f.name.split("_")[0] if "_" in f.name else f.name.split(".")[0]
                per_prefix[pfx] = per_prefix.get(pfx, 0) + 1
        breakdown = ", ".join(f"{pfx}_*: {n}" for pfx, n in sorted(per_prefix.items()))
        lines.append(f"- `{cell}` ({fmt}): **{corpus_sizes.get(cell, 0)} files** — {breakdown}")

    lines += [
        "",
        f"Generated {time.strftime('%Y-%m-%d %H:%M:%S')} from "
        f"`compares/results/mutation/biotest_fresh/`.",
    ]
    out_path = REPO_ROOT / "compares/results/mutation/biotest/RUN9_FRESH_BASELINE.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"wrote {out_path}")


def main():
    started = time.time()
    log("=== Run-9 fresh baseline (external seeds only) ===")

    # 1. Stage corpora
    corpus_sizes = {}
    for cell, sut, fmt, engine in CELLS:
        path = stage_external_corpus(cell, fmt)
        corpus_sizes[cell] = len(list(path.glob("*")))

    # 2. Launch all 6 cells in parallel
    cell_procs = {}
    for cell, sut, fmt, engine in CELLS:
        cell_procs[cell] = launch_cell(cell, sut, fmt, engine)

    # 3. Wait for all
    for cell, proc in cell_procs.items():
        rc = proc.wait()
        proc._biotest_log_fp.close()
        log(f"  {cell} exited rc={rc}")

    # 4. Collect results
    results = {}
    for cell, sut, fmt, engine in CELLS:
        r = read_summary(cell)
        if r is None:
            log(f"  {cell}: MISSING summary")
        else:
            log(f"  {cell}: killed={r['killed']} reach={r['reachable']} "
                f"score={r['score']*100:.2f}%")
        results[cell] = r

    log(f"=== aggregation (elapsed={int(time.time()-started)}s) ===")
    write_report(results, corpus_sizes)


if __name__ == "__main__":
    main()
