"""Render the Phase-3 mutation-score Markdown report for
Jazzer × htsjdk (both formats).

Consumes:
  compares/results/mutation/jazzer/htsjdk_{vcf,sam}/summary.json
  compares/results/mutation/jazzer/htsjdk_{vcf,sam}/baseline.json

Emits:
  compares/results/mutation/jazzer/mutation_score.md

The report mirrors Phase-2's coverage-growth aggregate structure so it
sits next to those files and can be linked from DESIGN.md §13.5 Phase 3.
Per-class Top-5 tables come straight from `summary.json`; baseline
distribution ({ok:N, err:C}) is a one-line histogram of the parse
outcomes the corpus produced on unmutated htsjdk — useful for the
reader to sanity-check that the corpus actually drives both the
happy-path and reject-path of the parser (if only `err:` outcomes
survived, the corpus never exercised record iteration and the score
is mostly uninformative).

Usage (run after compares/scripts/phase3_jazzer_pit.sh completes):
    py -3.12 compares/scripts/write_phase3_report.py
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MUT_ROOT = REPO_ROOT / "compares" / "results" / "mutation" / "jazzer"


def _load(fmt: str) -> tuple[dict, dict]:
    cell = MUT_ROOT / f"htsjdk_{fmt.lower()}"
    summary = json.loads((cell / "summary.json").read_text(encoding="utf-8"))
    baseline = json.loads((cell / "baseline.json").read_text(encoding="utf-8"))
    return summary, baseline


def _baseline_histogram(baseline: dict[str, str]) -> str:
    """One-line summary: `{ok: N, err.ClassA: X, err.ClassB: Y, ...}`."""
    c: Counter[str] = Counter()
    ok = 0
    for v in baseline.values():
        if v.startswith("ok:"):
            ok += 1
        else:
            c[v.split("err:", 1)[-1]] += 1
    parts = [f"ok: {ok}"]
    for name, n in c.most_common():
        short = name.rsplit(".", 1)[-1]
        parts.append(f"{short}: {n}")
    return ", ".join(parts)


def _render_top_classes(top5: list[dict]) -> str:
    if not top5:
        return "_(none — no classes had reachable mutations)_\n"
    lines = [
        "| class | killed | reachable | class-score |",
        "| :---- | :----: | :-------: | :---------: |",
    ]
    for r in top5:
        short = r["class"].rsplit(".", 1)[-1]
        lines.append(
            f"| `{short}` | {r['killed']} | {r['reachable']} | "
            f"{r['score']*100:.1f}% |"
        )
    return "\n".join(lines) + "\n"


def _render_status_table(s: dict) -> str:
    return (
        "| status | count |\n"
        "| :----- | ----: |\n"
        f"| KILLED       | {s['killed']} |\n"
        f"| SURVIVED     | {s['survived']} |\n"
        f"| NO_COVERAGE  | {s['no_coverage']} |\n"
        f"| TIMED_OUT    | {s['timed_out']} |\n"
        f"| NON_VIABLE   | {s['non_viable']} |\n"
        f"| MEMORY_ERROR | {s['memory_error']} |\n"
        f"| RUN_ERROR    | {s['run_error']} |\n"
        f"| **reachable** (KILLED + SURVIVED + TIMED_OUT) | **{s['reachable']}** |\n"
        f"| total        | {s['total_mutations']} |\n"
    )


def render() -> str:
    vcf_s, vcf_b = _load("VCF")
    sam_s, sam_b = _load("SAM")

    md = []
    md.append("# Phase 3 — Mutation Score · Jazzer × htsjdk\n")
    md.append(
        "> Generated by `compares/scripts/write_phase3_report.py` from "
        "`compares/results/mutation/jazzer/htsjdk_{vcf,sam}/summary.json` "
        "(PIT `mutations.xml`) + the corresponding `baseline.json`.\n"
    )
    md.append(
        "## Headline\n\n"
        "| cell | target classes | reachable | killed | survived | NO_COVERAGE | **score** |\n"
        "| :--- | :------------: | :-------: | :----: | :------: | :---------: | :-------: |\n"
        f"| Jazzer × htsjdk / **VCF** | {vcf_s['target_classes_n']} | "
        f"{vcf_s['reachable']} | {vcf_s['killed']} | {vcf_s['survived']} | "
        f"{vcf_s['no_coverage']} | **{vcf_s['score']*100:.2f}%** |\n"
        f"| Jazzer × htsjdk / **SAM** | {sam_s['target_classes_n']} | "
        f"{sam_s['reachable']} | {sam_s['killed']} | {sam_s['survived']} | "
        f"{sam_s['no_coverage']} | **{sam_s['score']*100:.2f}%** |\n"
    )
    md.append(
        "*`reachable = KILLED + SURVIVED + TIMED_OUT`* (DESIGN.md §3.3:"
        " \"reachable = mutants in code the corpus actually executed\""
        ").  *`score = killed / reachable`.*\n"
    )

    md.append(
        "## What's in scope\n\n"
        "PIT's `--targetClasses` list was produced by "
        "`compares/scripts/enumerate_target_classes.py` — which reads "
        "exactly the same rules "
        "`biotest_config.yaml:coverage.target_filters.{VCF,SAM}.htsjdk` "
        "the Phase-2 fairness recipe uses for coverage. That means:\n\n"
        "- **VCF**: `htsjdk.variant.vcf.*` + `htsjdk.variant.variantcontext.*` "
        "(excluding any `*JEXL*` / `*Jexl*` filter-expression classes per the "
        "`::-JEXL,-Jexl,-*JEXL*,-*Jexl*` rule) + `htsjdk.variant.variantcontext.writer.*` "
        "restricted to `VCF*` / `Variant*`-prefixed files via "
        "`::VCF,Variant`. **No BAM, CRAM, BCF, JEXL, or CLI** — BioTest's "
        "Jazzer harness never routes inputs to those.\n"
        "- **SAM**: `htsjdk.samtools::SAM,Sam` — only the `SAM*` / `Sam*` "
        "prefixed files in the `samtools` package. Drops index, BAM, "
        "CRAM, coordinate-conversion, and Picard-CLI utilities the harness "
        "never exercises.\n\n"
        "This is why the denominator is small (~80 / ~98 classes) instead "
        "of htsjdk's full ~900-class surface — mutating code the "
        "harness cannot reach would inflate `NO_COVERAGE` without "
        "adding any real kill-signal.\n"
    )

    md.append("## Corpus\n\n")
    md.append(
        "The corpus under test is the **union of the three Phase-2 "
        "Jazzer reps**' kept-corpus dirs "
        "(`compares/results/coverage/jazzer/htsjdk_<fmt>/run_<0,1,2>/corpus`) "
        f"deduped by filename, capped at {len(vcf_b)} (VCF) / {len(sam_b)} (SAM) "
        "files per cell — large enough to exercise the full parse path "
        "mix (ok + reject), small enough to stay inside the DESIGN.md "
        "§3.3 \"2h per cell\" mutation-testing budget. Lifted directly — "
        "no filtering; the whole point is to exercise the same parse "
        "paths the fuzzer drove.\n\n"
        "**Baseline outcome histogram** (VCFFileReader / SamReaderFactory "
        "outcome under unmutated htsjdk 4.1.1):\n\n"
        f"- **VCF** ({len(vcf_b)} files) — {_baseline_histogram(vcf_b)}\n"
        f"- **SAM** ({len(sam_b)} files) — {_baseline_histogram(sam_b)}\n\n"
        "A healthy corpus for mutation testing has both `ok:<N>` (successful "
        "iteration — exercises the record-parsing loop) and `err:*` "
        "(expected exception types — exercises the reject path); a "
        "mutant that flips either flavour gets caught.\n"
    )

    md.append("## PIT status breakdown · VCF\n\n")
    md.append(_render_status_table(vcf_s))
    md.append("\n### Top-5 classes by reachable mutants (VCF)\n\n")
    md.append(_render_top_classes(vcf_s["by_class_top5"]))

    md.append("\n## PIT status breakdown · SAM\n\n")
    md.append(_render_status_table(sam_s))
    md.append("\n### Top-5 classes by reachable mutants (SAM)\n\n")
    md.append(_render_top_classes(sam_s["by_class_top5"]))

    md.append(
        "\n## How this was produced\n\n"
        "One-command reproducer (inside `biotest-bench:latest`):\n\n"
        "```bash\n"
        "bash compares/scripts/phase3_jazzer_pit.sh\n"
        "# env overrides: FORMATS='VCF SAM' THREADS=6 CORPUS_MAX=200\n"
        "#                MUTATORS=DEFAULTS  MUTATION_UNIT_SIZE=5\n"
        "py -3.12 compares/scripts/write_phase3_report.py\n"
        "```\n\n"
        "Per-cell artefacts survive under "
        "`compares/results/mutation/jazzer/htsjdk_<fmt>/`: the combined "
        "corpus, the unmutated `baseline.json`, PIT's full HTML / XML "
        "report under `pit_report/`, and the parsed `summary.json` this "
        "report was rendered from.\n\n"
        "*Test-kill shape* — see `compares/scripts/phase3_pit/VCFMutationTest.java` "
        "and `SAMMutationTest.java`: one parameterless JUnit test that "
        "iterates the corpus once and asserts each file's outcome "
        "matches the precomputed `baseline.json`. A mutant is killed "
        "whenever any file's outcome string (`ok:<record-count>` or "
        "`err:<ExceptionClass>`) diverges from baseline — matching "
        "DESIGN.md §3.3's \"parse-success flip, canonical-JSON diff, "
        "crash flip\" kill criterion at the record-count / "
        "exception-class granularity.\n"
    )

    return "".join(md)


def _cli() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path,
                    default=MUT_ROOT / "mutation_score.md")
    args = ap.parse_args()
    md = render()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"[report] wrote {args.out} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
