"""Render the Phase-2 coverage-growth Markdown report for
Jazzer × htsjdk (both formats).

Companion to `write_phase3_report.py`. Consumes:
  compares/results/coverage/jazzer/htsjdk_{vcf,sam}/growth_{0,1,2}.json
  compares/results/coverage/jazzer/htsjdk_{vcf,sam}/growth_aggregate.json

Emits:
  compares/results/coverage/jazzer/coverage_growth.md

All numbers are pulled from the post-regrade JSONs (see
`compares/scripts/recompute_growth.py` + `measure_coverage.py`) so they
reflect the `biotest_config.yaml:coverage.target_filters.{VCF,SAM}.htsjdk`
fairness recipe — not the sampler's in-process hardcoded scope.

Usage::

    py -3.12 compares/scripts/write_phase2_report.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
COV_ROOT = REPO_ROOT / "compares" / "results" / "coverage" / "jazzer"


def _load(fmt: str) -> tuple[dict, list[dict], list[str]]:
    """Return (aggregate, [per_rep growth dicts], filter_rules)."""
    cell = COV_ROOT / f"htsjdk_{fmt.lower()}"
    agg = json.loads((cell / "growth_aggregate.json").read_text(encoding="utf-8"))
    reps = [
        json.loads(p.read_text(encoding="utf-8"))
        for p in sorted(cell.glob("growth_[0-9]*.json"))
    ]
    # Pull the active filter rules from biotest_config.yaml so the
    # report is self-describing — the scope is the same as what
    # measure_coverage.measure() applied during regrade.
    import yaml
    cfg = yaml.safe_load(
        (REPO_ROOT / "biotest_config.yaml").read_text(encoding="utf-8")
    )
    filter_rules = cfg["coverage"]["target_filters"][fmt.upper()]["htsjdk"]
    return agg, reps, filter_rules


def _format_agg_row(agg: dict, fmt: str) -> str:
    """One markdown row per tick for the growth table."""
    lines = [
        "| t_s | line mean % | line 95 % CI | branch mean % | branch 95 % CI |",
        "| ---: | :---------: | :-----------: | :-----------: | :-------------: |",
    ]
    for row in agg["coverage_growth_aggregate"]:
        lines.append(
            f"| {row['t_s']} | "
            f"{row['line_pct_mean']:.2f} | "
            f"[{row['line_pct_ci_lo']:.2f}, {row['line_pct_ci_hi']:.2f}] | "
            f"{row['branch_pct_mean']:.2f} | "
            f"[{row['branch_pct_ci_lo']:.2f}, {row['branch_pct_ci_hi']:.2f}] |"
        )
    return "\n".join(lines) + "\n"


def _format_per_rep_row(reps: list[dict]) -> str:
    """Per-rep final-tick table so the reader can eyeball variance
    without reopening the aggregate."""
    if not reps:
        return "_(no reps)_\n"
    # Pick the largest tick observed; usually 7200.
    final_t = max(
        int(s["t_s"]) for r in reps for s in r["coverage_growth"]
    )
    head = [
        f"| rep | line % @ t={final_t}s | branch % @ t={final_t}s | duration (s) |",
        "| :-: | :------------: | :-------------: | :---------: |",
    ]
    for r in reps:
        final = [s for s in r["coverage_growth"] if s["t_s"] == final_t]
        if not final:
            head.append(f"| {r['run_index']} | n/a | n/a | n/a |")
            continue
        f = final[0]
        dur = r.get("extra", {}).get("duration_s", "n/a")
        head.append(
            f"| {r['run_index']} | {f['line_pct']:.3f} | "
            f"{f['branch_pct']:.3f} | {dur} |"
        )
    return "\n".join(head) + "\n"


def _format_scope_bullets(filter_rules: list[str]) -> str:
    bullets = []
    for rule in filter_rules:
        bullets.append(f"  - `{rule}`")
    return "\n".join(bullets) + "\n"


def _count_corpus(cell: Path) -> dict[int, int]:
    """Count files under each rep's corpus dir (nominal Jazzer kept
    corpus — excluding crashes/ + reproducers/)."""
    out: dict[int, int] = {}
    for rep_dir in sorted(cell.glob("run_[0-9]*")):
        cdir = rep_dir / "corpus"
        out[int(rep_dir.name.split("_", 1)[1])] = (
            sum(1 for _ in cdir.iterdir()) if cdir.exists() else 0
        )
    return out


def render() -> str:
    vcf_agg, vcf_reps, vcf_rules = _load("VCF")
    sam_agg, sam_reps, sam_rules = _load("SAM")

    vcf_final = max(int(r["t_s"]) for r in vcf_agg["coverage_growth_aggregate"])
    sam_final = max(int(r["t_s"]) for r in sam_agg["coverage_growth_aggregate"])
    vcf_at_final = [r for r in vcf_agg["coverage_growth_aggregate"] if r["t_s"] == vcf_final][0]
    sam_at_final = [r for r in sam_agg["coverage_growth_aggregate"] if r["t_s"] == sam_final][0]

    vcf_corpus = _count_corpus(COV_ROOT / "htsjdk_vcf")
    sam_corpus = _count_corpus(COV_ROOT / "htsjdk_sam")

    md = []
    md.append("# Phase 2 — Coverage Growth · Jazzer × htsjdk\n")
    md.append(
        "> Generated by `compares/scripts/write_phase2_report.py` from "
        "`compares/results/coverage/jazzer/htsjdk_{vcf,sam}/growth_{0,1,2}.json` + "
        "`growth_aggregate.json`. All numbers are post-regrade against the "
        "fairness recipe (`biotest_config.yaml:coverage.target_filters` via "
        "`compares/scripts/measure_coverage.py`).\n"
    )

    md.append(
        "## Headline\n\n"
        f"| cell | reps | budget | **line % @ t={vcf_final}s (mean, 95 % CI)** | **branch % @ t={vcf_final}s (mean, 95 % CI)** |\n"
        "| :--- | :--: | :----: | :-------------------------------------: | :------------------------------------------: |\n"
        f"| Jazzer × htsjdk / **VCF** | {vcf_agg['reps']} | "
        f"{vcf_agg['time_budget_s']} s | "
        f"**{vcf_at_final['line_pct_mean']:.2f} %** "
        f"[{vcf_at_final['line_pct_ci_lo']:.2f}, {vcf_at_final['line_pct_ci_hi']:.2f}] | "
        f"**{vcf_at_final['branch_pct_mean']:.2f} %** "
        f"[{vcf_at_final['branch_pct_ci_lo']:.2f}, {vcf_at_final['branch_pct_ci_hi']:.2f}] |\n"
        f"| Jazzer × htsjdk / **SAM** | {sam_agg['reps']} | "
        f"{sam_agg['time_budget_s']} s | "
        f"**{sam_at_final['line_pct_mean']:.2f} %** "
        f"[{sam_at_final['line_pct_ci_lo']:.2f}, {sam_at_final['line_pct_ci_hi']:.2f}] | "
        f"**{sam_at_final['branch_pct_mean']:.2f} %** "
        f"[{sam_at_final['branch_pct_ci_lo']:.2f}, {sam_at_final['branch_pct_ci_hi']:.2f}] |\n\n"
        "*95 % CI = Student-t half-width across the 3 reps, reported by "
        "`recompute_growth._rebuild_aggregate`.*\n"
    )

    md.append(
        "## Sampling regime\n\n"
        "- **Budget**: 2 h (7200 s) per rep — DESIGN.md §3.2 primary.\n"
        "- **Reps**: 3 independent (different jacocoagent TCP ports per "
        "rep so concurrent reps wouldn't clash, even though they ran "
        "serially inside one container).\n"
        "- **Log ticks** (s): `{1, 10, 60, 300, 1800, 7200}`. At each "
        "tick the sampler calls `jacococli dump --reset=false` over the "
        "live TCP socket — snapshot without perturbing the fuzzer. Each "
        "`tick_<T>.exec` is converted to per-sourcefile XML at end of "
        "rep and filtered via `measure_coverage.measure()`.\n"
        "- **Fuzzer configuration**: Jazzer 0.22.1, "
        "`--keep_going=1000000` (Phase 2 is a coverage race, not a bug "
        "hunt), `--reproducer_path=<rep>/reproducers/` so "
        "`Crash_<hash>.java` stubs stay scoped, `-jvm_args=-javaagent:...`"
        " attaches the JaCoCo agent in tcpserver mode.\n"
        "- **Coverage scope**: `biotest_config.yaml:coverage.target_filters`"
        " — see next section.\n"
    )

    md.append(
        "## What's in scope (fairness recipe)\n\n"
        "Coverage is measured against the exact filter rules in "
        "`biotest_config.yaml`. Change them there, every measurement "
        "sees it; no scope is hardcoded in the sampler. Both numerator "
        "(covered lines) and denominator (total lines) honour the "
        "filter, so `LINE` + `BRANCH` %'s are comparable across tools "
        "(BioTest, Jazzer, Pure Random, EvoSuite) and across the three "
        "Run 6 grounding test (`tests/test_measure_coverage_cli.py`).\n\n"
        "**VCF filter rules** (`coverage.target_filters.VCF.htsjdk`):\n"
        f"{_format_scope_bullets(vcf_rules)}\n"
        "**SAM filter rules** (`coverage.target_filters.SAM.htsjdk`):\n"
        f"{_format_scope_bullets(sam_rules)}\n"
        "The `::-JEXL,-Jexl,-*JEXL*,-*Jexl*` / `::VCF,Variant` / "
        "`::SAM,Sam` suffixes are file-prefix include/exclude filters "
        "applied at the JaCoCo `sourcefile` level — see "
        "`test_engine/feedback/coverage_collector.py:parse_filter_rules`.\n"
    )

    md.append(
        "## VCF growth table\n\n"
        "Post-regrade, via `compares/scripts/measure_coverage.measure(..., metric='LINE'/'BRANCH')`. "
        "CI band = Student-t 95 % across the 3 reps.\n\n"
    )
    md.append(_format_agg_row(vcf_agg, "VCF"))
    md.append(
        "\n**Per-rep final-tick detail** (eyeballs the variance the CI "
        "band summarises):\n\n"
    )
    md.append(_format_per_rep_row(vcf_reps))

    md.append(
        "\n## SAM growth table\n\n"
    )
    md.append(_format_agg_row(sam_agg, "SAM"))
    md.append(
        "\n**Per-rep final-tick detail:**\n\n"
    )
    md.append(_format_per_rep_row(sam_reps))

    vcf_total = sum(vcf_corpus.values())
    sam_total = sum(sam_corpus.values())
    md.append(
        "\n## Corpus generated by Jazzer\n\n"
        "Jazzer's `corpus/` dir holds the inputs it decided to keep "
        "(i.e. those that widened the coverage frontier). These are the "
        "same files that feed Phase 3's mutation score.\n\n"
        "| format | run_0 | run_1 | run_2 | total (deduped downstream) |\n"
        "| :----: | :---: | :---: | :---: | :-----------------------: |\n"
        f"| VCF | {vcf_corpus.get(0, 0)} | {vcf_corpus.get(1, 0)} | "
        f"{vcf_corpus.get(2, 0)} | {vcf_total} |\n"
        f"| SAM | {sam_corpus.get(0, 0)} | {sam_corpus.get(1, 0)} | "
        f"{sam_corpus.get(2, 0)} | {sam_total} |\n"
    )

    md.append(
        "\n## How this was produced\n\n"
        "One-command reproducer (inside `biotest-bench:latest`; both "
        "cells run in parallel as separate detached containers via "
        "different TCP port bases):\n\n"
        "```bash\n"
        "# Launch (parallel, ~6 wall-hours total):\n"
        "docker run -d --name phase2-jazzer-vcf \\\n"
        "    -v \"$(pwd):/work\" -w /work \\\n"
        "    -e BUDGET_S=7200 -e REPS=3 -e FORMATS=VCF -e PORT_BASE=6300 \\\n"
        "    biotest-bench:latest bash compares/scripts/phase2_jazzer_htsjdk.sh\n"
        "docker run -d --name phase2-jazzer-sam \\\n"
        "    -v \"$(pwd):/work\" -w /work \\\n"
        "    -e BUDGET_S=7200 -e REPS=3 -e FORMATS=SAM -e PORT_BASE=6400 \\\n"
        "    biotest-bench:latest bash compares/scripts/phase2_jazzer_htsjdk.sh\n"
        "\n"
        "# Regrade against the fairness recipe (required — the running\n"
        "# containers had the sampler's old hardcoded scope cached in\n"
        "# memory; the refactored disk version never reloaded):\n"
        "py -3.12 compares/scripts/recompute_growth.py \\\n"
        "    --growth-dir compares/results/coverage/jazzer/htsjdk_vcf \\\n"
        "    --sut htsjdk --format VCF\n"
        "py -3.12 compares/scripts/recompute_growth.py \\\n"
        "    --growth-dir compares/results/coverage/jazzer/htsjdk_sam \\\n"
        "    --sut htsjdk --format SAM\n"
        "\n"
        "# Regenerate this report:\n"
        "py -3.12 compares/scripts/write_phase2_report.py\n"
        "```\n\n"
        "Per-cell artefacts under `compares/results/coverage/jazzer/htsjdk_<fmt>/`:\n\n"
        "- `growth_<0,1,2>.json` — per-rep tick snapshots (DESIGN.md §4.5 schema).\n"
        "- `growth_aggregate.json` — mean + 95 % CI across reps, tick-aligned.\n"
        "- `run_<0,1,2>/corpus/` — Jazzer's kept corpus per rep.\n"
        "- `run_<0,1,2>/jacoco_exec/tick_<T>.{exec,xml}` — raw JaCoCo snapshots.\n"
        "- `run_<0,1,2>/reproducers/` — per-finding `Crash_<hash>.java` stubs.\n"
        "- `run_<0,1,2>/tool.log` — Jazzer's libFuzzer-compatible progress log.\n"
        "- `phase2_jazzer_htsjdk.log` — driver log (cell boundaries + PIT handoff).\n"
    )

    return "".join(md)


def _cli() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path,
                    default=COV_ROOT / "coverage_growth.md")
    args = ap.parse_args()
    md = render()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"[report] wrote {args.out} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
